## Clear all object
switchtolayout;
selectall;
delete;


## Set some simpulation parameters
size_x = 3e-6;
size_y = 3e-6;
mesh_x = 20e-9;
mesh_y = 20e-9;
finer_mesh_size = 2.5e-6;
mesh_accuracy = 2;

## GEOMETRY

# Input waveguide
addrect;
set('name', 'input wg');
set('x span', 3e-6);
set('y span', 0.5e-6);
set('z span', 220e-9);
set('y', 0);
set('x', -2.5e-6);
set('index', 2.8);

# Output waveguide
addrect;
set('name', 'output wg top');
set('x span', 3e-6);
set('y span', 0.5e-6);
set('z span', 220e-9);
set('y', 0.35e-6);
set('x', 2.5e-6);
set('index', 2.8);

addrect;
set('name', 'output wg bottom');
set('x span', 3e-6);
set('y span', 0.5e-6);
set('z span', 220e-9);
set('y', -0.35e-6);
set('x', 2.5e-6);
set('index', 2.8);

## Source
addmode;
set('direction', 'Forward');
set('injection axis', 'x-axis');
set('y', 0.0);
set('y span', size_y);
set('x', -1.25e-6);
set('override global source settings', false);
set('mode selection', 'fundamental TE mode');

## FDTD
addfdtd;
set('dimension','2D');
set('background index', 1.44);
set('mesh accuracy', mesh_accuracy);
set('x', 0.0);
set('x span', size_x);
set('y', 0.0);
set('y span', size_y);
##Problem: requirement on source?
set('force symmetric y mesh', true);
set('y min bc', 'Anti-Symmetric');
set('pml layers', 12);

## Mesh in optimization region
addmesh;
set('x', 0);
##Problem: why add 2 mesh_x
set('x span', finer_mesh_size + 2.0 * mesh_x);
set('y', 0);
set('y span', finer_mesh_size);
set('dx', mesh_x);
set('dy', mesh_y);

## Optimization fields monitor in optimization region
addpower;
set('name', 'opt_fields');
set('monitor type', '2D Z-normal');
set('x', 0);
set('x span', finer_mesh_size);
set('y', 0);
set('y span', finer_mesh_size);

## FOM fields
addpower;
set('name', 'fom');
set('monitor type', '2D X-normal');
set('x', finer_mesh_size / 2);
set('y', 0.0);
set('y span', size_y);
